version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: mumble_auth
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
